name: Topher Timzen
url: http://www.tophertimzen.com
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

include:
 - _content
 - _markdowns

exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - README.md
 - _includes

# Build settings
paginate: 5
